### ISSUE TITLE
Python 3 syntax error in ./tools/split_wav.py

### ISSUE THREAD

**Issue by cclauss** [andabi/deep-voice-conversion#1]
flake8 testing of https://github.com/andabi/deep-voice-conversion on Python 3.6.3

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./tools/split_wav.py:45:16: E999 SyntaxError: invalid syntax
    map(lambda (i, w): write(w, sr, '{}/{}_{}.wav'.format(target_path, filename, i)), enumerate(split_wavs))
               ^
```

The () probably need to be removed so it reads:
```
map(lambda i, w: write(w, sr, '{}/{}_{}.wav'.format(target_path, filename, i)), enumerate(split_wavs))
```

**Comment by andabi** [comment]
@cclauss The code is written in Python 2.7. Thanks for the issue.

**Comment by cclauss** [comment]
https://pythonclock.org
