### ISSUE TITLE
How to train on the arctic dataset?

### ISSUE THREAD

**Issue by VictoriaBentell** [andabi/deep-voice-conversion#26]
If I'm understanding correctly, if we want to use train1 on the arctic dataset, we just need to do 
`python train1.py datasets/arctic/` right? It's stuck on the first epoch, and it's hard to tell if this is in the wrong format because it doesn't give a 'no such file or directory' error.

**Comment by VictoriaBentell** [comment]
Ok, looking through hparams.py, I now understand that I should be training on the TIMIT dataset, but I'm still encountering the same problem where it hangs on the first epoch. I put the TIMIT dataset in the 'datasets' folder, so according to line 49 in hparams.py, it should be pointing to the correct place. Is there anything I need to change in hparams.py or anywhere else?

**Comment by VictoriaBentell** [comment]
Ah, so it seems that it was looking for anything ending in .wav, but all of my audio files ended in .WAV. I just wrote a quick script to change all of the files from .WAV to .wav and all is well.

**Comment by Hjwjames** [comment]
![123123](https://user-images.githubusercontent.com/31679768/37318518-f23ace44-26a5-11e8-94bf-836b1bd4304c.png)

this is the problem I faced.....can you tell me why?...

**Comment by VictoriaBentell** [comment]
Try running it through the terminal with the command `python train1.py timit`
And just to be sure, you have the whole TIMIT dataset, right?

**Comment by Hjwjames** [comment]
Thank you for answering me !! You are very patient.
I found that I haven't put my TIMIT dataset in it.

**Comment by oracle9i88** [comment]
> Try running it through the terminal with the command `python train1.py timit`
> And just to be sure, you have the whole TIMIT dataset, right?
> Edit: Also be sure that the directory in data_path found in class Test1 in hparams.py matches the directory of your dataset. I had to move some folders around to get mine working.

I still cannot train

**Comment by LukeJacob** [comment]
where did u get TIMIT dataset? It is not for free so far as I know.

**Comment by rahulkhairnarr** [comment]
@LukeJacob You can download TIMIT from http://academictorrents.com/details/34e2b78745138186976cbc27939b1b34d18bd5b3
