### ISSUE TITLE
only "queue = False" worked ?

### ISSUE THREAD

**Issue by ThomasXu18** [andabi/deep-voice-conversion#29]
When i set "queue = False" to train net1, only take 3h. and the loss is 25%.
But when i use "queue = True" , its stuck.
GPU is GTX 1080Ti.
Thanks for help!

**Comment by vivek-sethia** [comment]
I have the same issue

**Comment by ThomasXu18** [comment]
@vivek-sethia 
I trained net 1 for 4000 epochs without queue. The loss is 70%.
and triand net2 for 10000+ epochs. The result is not perfect.
I am trying to improve it for better results
