### ISSUE TITLE
How long train2 works?

### ISSUE THREAD

**Issue by woogotcha** [andabi/deep-voice-conversion#43]
I used Artic/slt to target voice datasets in train2.py.
And I used Artic/bdl to input voice datasets in converter.py.

It is still in operation and has exceeded about 48 hours below image.
![image](https://user-images.githubusercontent.com/25999433/40708827-65f3934a-642f-11e8-83bc-776c145e04ae.png)

Additionally, this environment uses NDVIA TITAN X (Pascal) 12G GPU.
Now epoch is 3050 and step is 94550.

When does it finish running?

**Comment by iamxiaoyubei** [comment]
+1! 
Could I stop train2 when I have not reached the epoch of 10000, and when should I stop train2?
