### ISSUE TITLE
Run train1.py error. No module name tfplot

### ISSUE THREAD

**Issue by wojingdaile** [andabi/deep-voice-conversion#44]
Hi, I met this problem, does the module "tfplot" missing?

```
python train1.py 
Traceback (most recent call last):
  File "train1.py", line 17, in <module>
    from data_load import Net1DataFlow
  File "/Users/yafengtang/Private/CelebritiesVoice/deep-voice-conversion/data_load.py", line 14, in <module>
    from utils import normalize_0_1
  File "/Users/yafengtang/Private/CelebritiesVoice/deep-voice-conversion/utils.py", line 12, in <module>
    import tfplot
ImportError: No module named tfplot
```

Anybody knows where "tfplot" is?

**Comment by ryancwalsh** [comment]
@wojingdaile Why did you close this issue?    I'm having the same exact problem.  What was the solution? Thanks.

**Comment by ryancwalsh** [comment]
I did a system-wide search for "tfplot" on my computer and found 2 folders:

- C:\code\Anaconda\envs\deep-voice-conversion\Lib\site-packages\tfplot-0.2.0.dev0.dist-info
- C:\code\Anaconda\envs\deep-voice-conversion\Lib\site-packages\tfplot

I copied them both to `C:\code\Anaconda\envs\tensorflow\Lib\site-packages`, and now I don't have the error.
