### ISSUE TITLE
Stuck when running train1

### ISSUE THREAD

**Issue by asssssasssssin** [andabi/deep-voice-conversion#47]
I have put the TIMIT dataset in './datasets', and set the corresponding datapath in 'default.yaml'.

When I ran 'python3 train1.py case', an error showed up looked like this:
![untitled](https://user-images.githubusercontent.com/34438161/41500122-f8ee3ca8-71be-11e8-8051-82be74348027.png)
Then it finally stuck at here: 
![image](https://user-images.githubusercontent.com/34438161/41499645-f61b1a54-71b5-11e8-9eea-686ccd400667.png)

Does anyone have any idea to solve this problem? Please let me know. Thank you.

**Comment by asssssasssssin** [comment]
I used 
https://github.com/andabi/deep-voice-conversion/tree/ba7dab2fa603efbd2099c1ceba177f3668155664 
, and modify by
https://github.com/andabi/deep-voice-conversion/pull/30
, then it worked.

But it got acc: 0.0066193854, loss: 4.800442, at train1. I found it stop at epoch1 and done!

**Comment by iamxiaoyubei** [comment]
> I used
> https://github.com/andabi/deep-voice-conversion/tree/ba7dab2fa603efbd2099c1ceba177f3668155664
> , and modify by
> #30
> , then it worked.
> 
> But it got acc: 0.0066193854, loss: 4.800442, at train1. I found it stop at epoch1 and done!

acc: 0.011408651
loss: 4.5185957
I also got the same problem. Have you solved it? Plz help me! Thank you!

**Comment by iamxiaoyubei** [comment]
> I used
> https://github.com/andabi/deep-voice-conversion/tree/ba7dab2fa603efbd2099c1ceba177f3668155664
> , and modify by
> #30
> , then it worked.
> 
> But it got acc: 0.0066193854, loss: 4.800442, at train1. I found it stop at epoch1 and done!

acc: 0.011408651
loss: 4.5185957
@asssssasssssin 
After doing your instruction, I also got the same problem with you. Have you solved it? Plz help me! Thank you!
