### ISSUE TITLE
May I ask you a question?

### ISSUE THREAD

**Issue by day18s** [andabi/deep-voice-conversion#6]
Hello. 
Does intonation, loudness of speech and etc. taken into account while convertion?
If you will change the input statement into a question only intonationally, will the output also change?

Thank you.

**Comment by andabi** [comment]
@day18s Hi. The source speaker's intonation, loudness will be gone because the connection between speeches is only phoneme at present. I consider it as advanced topics like catching source speaker's intonation when synthesizing target speaker's speeches. Any idea?

**Comment by day18s** [comment]
Hello @andabi.
Thanks for your reply.
As far as I understand, the information on intonation is still availible at the stage. Isn't it? 
Not sure whether it is possible and will make any sense to convert mfccs.
