### ISSUE TITLE
data_load.py error

### ISSUE THREAD

**Issue by Enderpman** [andabi/deep-voice-conversion#69]
Windows 10 Pro
Intel Core i7 6800K
tqdm 4.23.2
tensorflow 1.5.0
tensorpack 0.9.0
Here's my code:
$ py train1.py -case timit
case: timit, logdir: cases/timit/train1
[32m[1105 18:49:05 @logger.py:108][0m [5m[31mWRN[0m Log directory cases/timit/train1 exists! Use 'd' to delete it. 
[32m[1105 18:49:05 @logger.py:111][0m [5m[31mWRN[0m If you're resuming from a previous run, you can choose to keep it.
Press any other key to exit.
Select Action: k (keep) / d (delete) / q (quit):k
[32m[1105 18:49:07 @logger.py:66][0m Existing log file 'cases/timit/train1\log.log' backuped to 'cases/timit/train1\log.log.1105-184907'
[32m[1105 18:49:07 @logger.py:73][0m Argv: train1.py -case timit
[32m[1105 18:49:07 @parallel.py:176][0m [5m[31mWRN[0m MultiProcessPrefetchData does support windows. However, windows requires more strict picklability on processes, which may lead of failure on some of the code.
[32m[1105 18:49:07 @parallel.py:186][0m [MultiProcessPrefetchData] Will fork a dataflow more than one times. This assumes the datapoints are i.i.d.
[32m[1105 18:49:07 @sesscreate.py:38][0m [5m[31mWRN[0m User-provided custom session config may not work due to TF bugs. See https://github.com/tensorpack/tensorpack/issues/497 for workarounds.
[32m[1105 18:49:07 @develop.py:96][0m [5m[31mWRN[0m [Deprecated] ModelDescBase._get_inputs() interface will be deprecated after 30 Mar. Use inputs() instead!
[32m[1105 18:49:07 @input_source.py:220][0m Setting up the queue 'QueueInput/input_queue' for CPU prefetching ...
[32m[1105 18:49:07 @training.py:112][0m Building graph for training tower 0 on device /gpu:0 ...
[32m[1105 18:49:07 @develop.py:96][0m [5m[31mWRN[0m [Deprecated] ModelDescBase._build_graph() interface will be deprecated after 30 Mar. Use build_graph() instead!
[32m[1105 18:49:08 @develop.py:96][0m [5m[31mWRN[0m [Deprecated] get_cost() and self.cost will be deprecated after 30 Mar. Return the cost tensor directly in build_graph() instead!
[32m[1105 18:49:08 @develop.py:96][0m [5m[31mWRN[0m [Deprecated] ModelDescBase._get_optimizer() interface will be deprecated after 30 Mar. Use optimizer() instead!
[32m[1105 18:49:10 @training.py:322][0m 'sync_variables_from_main_tower' includes 0 operations.
[32m[1105 18:49:10 @model_utils.py:64][0m [36mTrainable Variables:
[0mname                                                            shape           dim
--------------------------------------------------------------  ------------  -----
net1/prenet/dense1/kernel:0                                     [60, 128]      7680
net1/prenet/dense1/bias:0                                       [128]           128
net1/prenet/dense2/kernel:0                                     [128, 64]      8192
net1/prenet/dense2/bias:0                                       [64]             64
net1/cbhg/conv1d_banks/num_1/conv1d/conv1d/kernel:0             [1, 64, 64]    4096
net1/cbhg/conv1d_banks/num_1/normalize/beta:0                   [64]             64
net1/cbhg/conv1d_banks/num_1/normalize/gamma:0                  [64]             64
net1/cbhg/conv1d_banks/num_2/conv1d/conv1d/kernel:0             [2, 64, 64]    8192
net1/cbhg/conv1d_banks/num_2/normalize/beta:0                   [64]             64
net1/cbhg/conv1d_banks/num_2/normalize/gamma:0                  [64]             64
net1/cbhg/conv1d_banks/num_3/conv1d/conv1d/kernel:0             [3, 64, 64]   12288
net1/cbhg/conv1d_banks/num_3/normalize/beta:0                   [64]             64
net1/cbhg/conv1d_banks/num_3/normalize/gamma:0                  [64]             64
net1/cbhg/conv1d_banks/num_4/conv1d/conv1d/kernel:0             [4, 64, 64]   16384
net1/cbhg/conv1d_banks/num_4/normalize/beta:0                   [64]             64
net1/cbhg/conv1d_banks/num_4/normalize/gamma:0                  [64]             64
net1/cbhg/conv1d_banks/num_5/conv1d/conv1d/kernel:0             [5, 64, 64]   20480
net1/cbhg/conv1d_banks/num_5/normalize/beta:0                   [64]             64
net1/cbhg/conv1d_banks/num_5/normalize/gamma:0                  [64]             64
net1/cbhg/conv1d_banks/num_6/conv1d/conv1d/kernel:0             [6, 64, 64]   24576
net1/cbhg/conv1d_banks/num_6/normalize/beta:0                   [64]             64
net1/cbhg/conv1d_banks/num_6/normalize/gamma:0                  [64]             64
net1/cbhg/conv1d_banks/num_7/conv1d/conv1d/kernel:0             [7, 64, 64]   28672
net1/cbhg/conv1d_banks/num_7/normalize/beta:0                   [64]             64
net1/cbhg/conv1d_banks/num_7/normalize/gamma:0                  [64]             64
net1/cbhg/conv1d_banks/num_8/conv1d/conv1d/kernel:0             [8, 64, 64]   32768
net1/cbhg/conv1d_banks/num_8/normalize/beta:0                   [64]             64
net1/cbhg/conv1d_banks/num_8/normalize/gamma:0                  [64]             64
net1/cbhg/conv1d_1/conv1d/kernel:0                              [3, 512, 64]  98304
net1/cbhg/normalize/beta:0                                      [64]             64
net1/cbhg/normalize/gamma:0                                     [64]             64
net1/cbhg/conv1d_2/conv1d/kernel:0                              [3, 64, 64]   12288
net1/cbhg/highwaynet_0/dense1/kernel:0                          [64, 64]       4096
net1/cbhg/highwaynet_0/dense1/bias:0                            [64]             64
net1/cbhg/highwaynet_0/dense2/kernel:0                          [64, 64]       4096
net1/cbhg/highwaynet_0/dense2/bias:0                            [64]             64
net1/cbhg/highwaynet_1/dense1/kernel:0                          [64, 64]       4096
net1/cbhg/highwaynet_1/dense1/bias:0                            [64]             64
net1/cbhg/highwaynet_1/dense2/kernel:0                          [64, 64]       4096
net1/cbhg/highwaynet_1/dense2/bias:0                            [64]             64
net1/cbhg/highwaynet_2/dense1/kernel:0                          [64, 64]       4096
net1/cbhg/highwaynet_2/dense1/bias:0                            [64]             64
net1/cbhg/highwaynet_2/dense2/kernel:0                          [64, 64]       4096
net1/cbhg/highwaynet_2/dense2/bias:0                            [64]             64
net1/cbhg/highwaynet_3/dense1/kernel:0                          [64, 64]       4096
net1/cbhg/highwaynet_3/dense1/bias:0                            [64]             64
net1/cbhg/highwaynet_3/dense2/kernel:0                          [64, 64]       4096
net1/cbhg/highwaynet_3/dense2/bias:0                            [64]             64
net1/cbhg/gru/bidirectional_rnn/fw/gru_cell/gates/kernel:0      [128, 128]    16384
net1/cbhg/gru/bidirectional_rnn/fw/gru_cell/gates/bias:0        [128]           128
net1/cbhg/gru/bidirectional_rnn/fw/gru_cell/candidate/kernel:0  [128, 64]      8192
net1/cbhg/gru/bidirectional_rnn/fw/gru_cell/candidate/bias:0    [64]             64
net1/cbhg/gru/bidirectional_rnn/bw/gru_cell/gates/kernel:0      [128, 128]    16384
net1/cbhg/gru/bidirectional_rnn/bw/gru_cell/gates/bias:0        [128]           128
net1/cbhg/gru/bidirectional_rnn/bw/gru_cell/candidate/kernel:0  [128, 64]      8192
net1/cbhg/gru/bidirectional_rnn/bw/gru_cell/candidate/bias:0    [64]             64
net1/dense/kernel:0                                             [128, 61]      7808
net1/dense/bias:0                                               [61]             61[36m
Total #vars=58, #params=365949, size=1.40MB[0m
[32m[1105 18:49:10 @base.py:209][0m Setup callbacks graph ...
[32m[1105 18:49:10 @summary.py:38][0m Maintain moving average summary of 0 tensors in collection MOVING_SUMMARY_OPS.
[32m[1105 18:49:10 @summary.py:75][0m Summarizing collection 'summaries' of size 3.
[32m[1105 18:49:11 @base.py:227][0m Creating the session ...
2018-11-05 18:49:11.598112: I C:\tf_jenkins\workspace\rel-win\M\windows\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
[32m[1105 18:49:12 @base.py:233][0m Initializing the session ...
[32m[1105 18:49:12 @base.py:240][0m Graph Finalized.
[32m[1105 18:49:12 @concurrency.py:37][0m Starting EnqueueThread QueueInput/input_queue ...
[32m[1105 18:49:12 @graph.py:73][0m Running Op sync_variables/sync_variables_from_main_tower ...
Process _Worker-4:
Process _Worker-2:
Traceback (most recent call last):
  File "C:\Users\kevin\AppData\Local\Programs\Python\Python36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
Process _Worker-5:
  File "C:\Users\kevin\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorpack\dataflow\parallel.py", line 163, in run
    for dp in self.ds:
Traceback (most recent call last):
  File "C:\Users\kevin\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorpack\dataflow\common.py", line 116, in __iter__
    for data in self.ds:
Process _Worker-1:
  File "C:\Users\kevin\AppData\Local\Programs\Python\Python36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "D:\Documents\GitHub\deep-voice-conversion\data_load.py", line 32, in get_data
    wav_file = random.choice(self.wav_files)
  File "C:\Users\kevin\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorpack\dataflow\parallel.py", line 163, in run
    for dp in self.ds:
  File "C:\Users\kevin\AppData\Local\Programs\Python\Python36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Users\kevin\AppData\Local\Programs\Python\Python36\lib\random.py", line 257, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
Traceback (most recent call last):
  File "C:\Users\kevin\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorpack\dataflow\common.py", line 116, in __iter__
    for data in self.ds:
Process _Worker-3:
  File "C:\Users\kevin\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorpack\dataflow\parallel.py", line 163, in run
    for dp in self.ds:
IndexError: Cannot choose from an empty sequence
  File "C:\Users\kevin\AppData\Local\Programs\Python\Python36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "D:\Documents\GitHub\deep-voice-conversion\data_load.py", line 32, in get_data
    wav_file = random.choice(self.wav_files)
  File "C:\Users\kevin\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorpack\dataflow\common.py", line 116, in __iter__
    for data in self.ds:
  File "C:\Users\kevin\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorpack\dataflow\parallel.py", line 163, in run
    for dp in self.ds:
  File "C:\Users\kevin\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorpack\dataflow\common.py", line 116, in __iter__
    for data in self.ds:
  File "C:\Users\kevin\AppData\Local\Programs\Python\Python36\lib\random.py", line 257, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
  File "D:\Documents\GitHub\deep-voice-conversion\data_load.py", line 32, in get_data
    wav_file = random.choice(self.wav_files)
Traceback (most recent call last):
  File "D:\Documents\GitHub\deep-voice-conversion\data_load.py", line 32, in get_data
    wav_file = random.choice(self.wav_files)
  File "C:\Users\kevin\AppData\Local\Programs\Python\Python36\lib\random.py", line 257, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
  File "C:\Users\kevin\AppData\Local\Programs\Python\Python36\lib\random.py", line 257, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
  File "C:\Users\kevin\AppData\Local\Programs\Python\Python36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Users\kevin\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorpack\dataflow\parallel.py", line 163, in run
    for dp in self.ds:
IndexError: Cannot choose from an empty sequence
IndexError: Cannot choose from an empty sequence
IndexError: Cannot choose from an empty sequence
  File "C:\Users\kevin\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorpack\dataflow\common.py", line 116, in __iter__
    for data in self.ds:
  File "D:\Documents\GitHub\deep-voice-conversion\data_load.py", line 32, in get_data
    wav_file = random.choice(self.wav_files)
  File "C:\Users\kevin\AppData\Local\Programs\Python\Python36\lib\random.py", line 257, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
[32m[1105 18:49:13 @base.py:272][0m Start Epoch 1 ...
  0%|                                                                                             |0/100[00:00<?,?it/s]

**Comment by wuzhiyu666** [comment]
+1 ！！！

**Comment by wuzhiyu666** [comment]
I meet the same problem as you

**Comment by wuzhiyu666** [comment]
Have you solve the problem now?

**Comment by wishvivek** [comment]
Most probably you have not set the data path in the /hparams/default.yaml file. This is why when it is trying to read a wave file in data_load.py line 32, it is not getting any file. Hence, the error 'IndexError: Cannot choose from an empty sequence'. So, please set the path to the TIMIT dataset in /hparams/default.yaml.
