### ISSUE TITLE
PHN files in training data?

### ISSUE THREAD

**Issue by wanshun123** [andabi/deep-voice-conversion#71]
In `data_load.py` there is the following code:

```
    phn_file = wav_file.replace("WAV.wav", "PHN").replace("wav", "PHN")
    phn2idx, idx2phn = load_vocab()
    phns = np.zeros(shape=(num_timesteps,))
    bnd_list = []
    for line in open(phn_file, 'r').read().splitlines():
        start_point, _, phn = line.split()
        bnd = int(start_point) // hp.default.hop_length
        phns[bnd:] = phn2idx[phn]
        bnd_list.append(bnd)
```

So there are supposed to be PHN files in the training data to match the wav files. Where are these found/generated? In the current repo there are only wav files (https://github.com/andabi/deep-voice-conversion/tree/master/datasets/arctic/bdl).

**Comment by sailor88128** [comment]
Check readme, TIMIT data should be used for Net1 train.
