### ISSUE TITLE
My loss for net2 is very small from the beginning(nearly 0.016, and reduced to approximately 0.010 after 20k steps)

### ISSUE THREAD

**Issue by stephen-song** [andabi/deep-voice-conversion#86]

**Comment by stephen-song** [comment]
This doesn't seem to be normal，Has anyone encountered this problem like me?（i used arctic dataset for net2）

**Comment by iamxiaoyubei** [comment]
@wishvivek My situation is exactly the same as yours. Is there something wrong? Have you successfully trained Net2? Could you please tell me how long will it take or how long could I stop it?(because it is too long to run 10000 epochs...) Thank you!!

**Comment by stephen-song** [comment]
hey guys, I successfully run the code and got some audible results . u can dawnload it and have a test.
[audio.zip](https://github.com/andabi/deep-voice-conversion/files/2726158/audio.zip)
i trained net1 with TIMIT and got accrucy of 0.70(test acc, not train acc which is about 0.85) at around 100 epoch, loss for Net2 decreased from 0.016 to 0.0058 at 600 epoch. In the above zip file ,i also upload
conversion results from different epochs of training（Marked by loss value）.
