### ISSUE TITLE
Help on train2.py

### ISSUE THREAD

**Issue by YashBangera7** [andabi/deep-voice-conversion#89]
Can someone please tell me how to run train2.py ? 
I have already trained train1.py and tested it using eval1.py have a case generated as TIMIT_ACTUAL1 . 
I do not understand what to use as the arguments for train2

**Comment by Huishou** [comment]
Hi，If you work in Pycharm， just check the train2.py. Do you have any problem with running it?

**Comment by YashBangera7** [comment]
> Hi，If you work in Pycharm， just check the train2.py. Do you have any problem with running it?

Yeah . Actually I was running it on windows 10 . Succesfully got off running train1.py on NVIDIA GTX 1050 Ti   and unable to run the train2.py . No idea about the -case arguments and how to run it . It would be really helpful if you could suggest me the procedure.  Running it through anaconda prompt on the gpu

**Comment by YashBangera7** [comment]
The entire command is as follows :
(dlwin36) C:\Users\Yash\Downloads\Deep Voice\deep-voice-conversion-master>python train2.py -case TIMIT_ACTUAL1 -gpu 0
case: TIMIT_ACTUAL1, logdir1: cases/TIMIT_ACTUAL1/train1, logdir2: cases/TIMIT_ACTUAL1/train2
[32m[0130 22:20:11 @logger.py:108][0m [5m[31mWRN[0m Log directory cases/TIMIT_ACTUAL1/train2 exists! Use 'd' to delete it.
[32m[0130 22:20:11 @logger.py:111][0m [5m[31mWRN[0m If you're resuming from a previous run, you can choose to keep it.
Press any other key to exit.
Select Action: k (keep) / d (delete) / q (quit):d
[32m[0130 22:20:13 @logger.py:73][0m Argv: train2.py -case TIMIT_ACTUAL1 -gpu 0
[32m[0130 22:20:13 @parallel.py:176][0m [5m[31mWRN[0m MultiProcessPrefetchData does support windows. However, windows requires more strict picklability on processes, which may lead of failure on some of the code.
[32m[0130 22:20:13 @parallel.py:186][0m [MultiProcessPrefetchData] Will fork a dataflow more than one times. This assumes the datapoints are i.i.d.
C:\Users\Yash\anaconda\envs\dlwin36\lib\site-packages\librosa\effects.py:486: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  return y[full_index], np.asarray([start, end])
C:\Users\Yash\anaconda\envs\dlwin36\lib\site-packages\librosa\util\utils.py:343: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  return data[slices]
C:\Users\Yash\anaconda\envs\dlwin36\lib\site-packages\librosa\effects.py:486: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  return y[full_index], np.asarray([start, end])
C:\Users\Yash\anaconda\envs\dlwin36\lib\site-packages\librosa\util\utils.py:343: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  return data[slices]
C:\Users\Yash\anaconda\envs\dlwin36\lib\site-packages\librosa\effects.py:486: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  return y[full_index], np.asarray([start, end])
C:\Users\Yash\anaconda\envs\dlwin36\lib\site-packages\librosa\util\utils.py:343: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  return data[slices]
C:\Users\Yash\anaconda\envs\dlwin36\lib\site-packages\librosa\effects.py:486: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  return y[full_index], np.asarray([start, end])
C:\Users\Yash\anaconda\envs\dlwin36\lib\site-packages\librosa\util\utils.py:343: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  return data[slices]
[32m[0130 22:22:35 @sesscreate.py:38][0m [5m[31mWRN[0m User-provided custom session config may not work due to TF bugs. See https://github.com/tensorpack/tensorpack/issues/497 for workarounds.
[32m[0130 22:22:35 @config.py:165][0m [5m[31mWRN[0m TrainConfig.nr_tower was deprecated! Set the number of GPUs on the trainer instead!
[32m[0130 22:22:35 @config.py:166][0m [5m[31mWRN[0m See https://github.com/tensorpack/tensorpack/issues/458 for more information.
[32m[0130 22:22:35 @develop.py:96][0m [5m[31mWRN[0m [Deprecated] ModelDescBase._get_inputs() interface will be deprecated after 30 Mar. Use inputs() instead!
[32m[0130 22:22:35 @input_source.py:220][0m Setting up the queue 'QueueInput/input_queue' for CPU prefetching ...
[32m[0130 22:22:35 @trainers.py:52][0m Building graph for a single training tower ...
[32m[0130 22:22:35 @develop.py:96][0m [5m[31mWRN[0m [Deprecated] ModelDescBase._build_graph() interface will be deprecated after 30 Mar. Use build_graph() instead!
C:\Users\Yash\anaconda\envs\dlwin36\lib\site-packages\librosa\effects.py:486: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  return y[full_index], np.asarray([start, end])
C:\Users\Yash\anaconda\envs\dlwin36\lib\site-packages\librosa\util\utils.py:343: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  return data[slices]
[32m[0130 22:22:46 @develop.py:96][0m [5m[31mWRN[0m [Deprecated] get_cost() and self.cost will be deprecated after 30 Mar. Return the cost tensor directly in build_graph() instead!
[32m[0130 22:22:46 @develop.py:96][0m [5m[31mWRN[0m [Deprecated] ModelDescBase._get_optimizer() interface will be deprecated after 30 Mar. Use optimizer() instead!
[32m[0130 22:23:11 @model_utils.py:64][0m [36mTrainable Variables:
[0mname                                                                   shape              dim
---------------------------------------------------------------------  --------------  ------
net1/prenet/dense1/kernel:0                                            [60, 128]         7680
net1/prenet/dense1/bias:0                                              [128]              128
net1/prenet/dense2/kernel:0                                            [128, 64]         8192
net1/prenet/dense2/bias:0                                              [64]                64
net1/cbhg/conv1d_banks/num_1/conv1d/conv1d/kernel:0                    [1, 64, 64]       4096
net1/cbhg/conv1d_banks/num_1/normalize/beta:0                          [64]                64
net1/cbhg/conv1d_banks/num_1/normalize/gamma:0                         [64]                64
net1/cbhg/conv1d_banks/num_2/conv1d/conv1d/kernel:0                    [2, 64, 64]       8192
net1/cbhg/conv1d_banks/num_2/normalize/beta:0                          [64]                64
net1/cbhg/conv1d_banks/num_2/normalize/gamma:0                         [64]                64
net1/cbhg/conv1d_banks/num_3/conv1d/conv1d/kernel:0                    [3, 64, 64]      12288
net1/cbhg/conv1d_banks/num_3/normalize/beta:0                          [64]                64
net1/cbhg/conv1d_banks/num_3/normalize/gamma:0                         [64]                64
net1/cbhg/conv1d_banks/num_4/conv1d/conv1d/kernel:0                    [4, 64, 64]      16384
net1/cbhg/conv1d_banks/num_4/normalize/beta:0                          [64]                64
net1/cbhg/conv1d_banks/num_4/normalize/gamma:0                         [64]                64
net1/cbhg/conv1d_banks/num_5/conv1d/conv1d/kernel:0                    [5, 64, 64]      20480
net1/cbhg/conv1d_banks/num_5/normalize/beta:0                          [64]                64
net1/cbhg/conv1d_banks/num_5/normalize/gamma:0                         [64]                64
net1/cbhg/conv1d_banks/num_6/conv1d/conv1d/kernel:0                    [6, 64, 64]      24576
net1/cbhg/conv1d_banks/num_6/normalize/beta:0                          [64]                64
net1/cbhg/conv1d_banks/num_6/normalize/gamma:0                         [64]                64
net1/cbhg/conv1d_banks/num_7/conv1d/conv1d/kernel:0                    [7, 64, 64]      28672
net1/cbhg/conv1d_banks/num_7/normalize/beta:0                          [64]                64
net1/cbhg/conv1d_banks/num_7/normalize/gamma:0                         [64]                64
net1/cbhg/conv1d_banks/num_8/conv1d/conv1d/kernel:0                    [8, 64, 64]      32768
net1/cbhg/conv1d_banks/num_8/normalize/beta:0                          [64]                64
net1/cbhg/conv1d_banks/num_8/normalize/gamma:0                         [64]                64
net1/cbhg/conv1d_1/conv1d/kernel:0                                     [3, 512, 64]     98304
net1/cbhg/normalize/beta:0                                             [64]                64
net1/cbhg/normalize/gamma:0                                            [64]                64
net1/cbhg/conv1d_2/conv1d/kernel:0                                     [3, 64, 64]      12288
net1/cbhg/highwaynet_0/dense1/kernel:0                                 [64, 64]          4096
net1/cbhg/highwaynet_0/dense1/bias:0                                   [64]                64
net1/cbhg/highwaynet_0/dense2/kernel:0                                 [64, 64]          4096
net1/cbhg/highwaynet_0/dense2/bias:0                                   [64]                64
net1/cbhg/highwaynet_1/dense1/kernel:0                                 [64, 64]          4096
net1/cbhg/highwaynet_1/dense1/bias:0                                   [64]                64
net1/cbhg/highwaynet_1/dense2/kernel:0                                 [64, 64]          4096
net1/cbhg/highwaynet_1/dense2/bias:0                                   [64]                64
net1/cbhg/highwaynet_2/dense1/kernel:0                                 [64, 64]          4096
net1/cbhg/highwaynet_2/dense1/bias:0                                   [64]                64
net1/cbhg/highwaynet_2/dense2/kernel:0                                 [64, 64]          4096
net1/cbhg/highwaynet_2/dense2/bias:0                                   [64]                64
net1/cbhg/highwaynet_3/dense1/kernel:0                                 [64, 64]          4096
net1/cbhg/highwaynet_3/dense1/bias:0                                   [64]                64
net1/cbhg/highwaynet_3/dense2/kernel:0                                 [64, 64]          4096
net1/cbhg/highwaynet_3/dense2/bias:0                                   [64]                64
net1/cbhg/gru/bidirectional_rnn/fw/gru_cell/gates/kernel:0             [128, 128]       16384
net1/cbhg/gru/bidirectional_rnn/fw/gru_cell/gates/bias:0               [128]              128
net1/cbhg/gru/bidirectional_rnn/fw/gru_cell/candidate/kernel:0         [128, 64]         8192
net1/cbhg/gru/bidirectional_rnn/fw/gru_cell/candidate/bias:0           [64]                64
net1/cbhg/gru/bidirectional_rnn/bw/gru_cell/gates/kernel:0             [128, 128]       16384
net1/cbhg/gru/bidirectional_rnn/bw/gru_cell/gates/bias:0               [128]              128
net1/cbhg/gru/bidirectional_rnn/bw/gru_cell/candidate/kernel:0         [128, 64]         8192
net1/cbhg/gru/bidirectional_rnn/bw/gru_cell/candidate/bias:0           [64]                64
net1/dense/kernel:0                                                    [128, 61]         7808
net1/dense/bias:0                                                      [61]                61
net2/prenet/dense1/kernel:0                                            [61, 256]        15616
net2/prenet/dense1/bias:0                                              [256]              256
net2/prenet/dense2/kernel:0                                            [256, 128]       32768
net2/prenet/dense2/bias:0                                              [128]              128
net2/cbhg_mel/conv1d_banks/num_1/conv1d/conv1d/kernel:0                [1, 128, 128]    16384
net2/cbhg_mel/conv1d_banks/num_1/normalize/beta:0                      [128]              128
net2/cbhg_mel/conv1d_banks/num_1/normalize/gamma:0                     [128]              128
net2/cbhg_mel/conv1d_banks/num_2/conv1d/conv1d/kernel:0                [2, 128, 128]    32768
net2/cbhg_mel/conv1d_banks/num_2/normalize/beta:0                      [128]              128
net2/cbhg_mel/conv1d_banks/num_2/normalize/gamma:0                     [128]              128
net2/cbhg_mel/conv1d_banks/num_3/conv1d/conv1d/kernel:0                [3, 128, 128]    49152
net2/cbhg_mel/conv1d_banks/num_3/normalize/beta:0                      [128]              128
net2/cbhg_mel/conv1d_banks/num_3/normalize/gamma:0                     [128]              128
net2/cbhg_mel/conv1d_banks/num_4/conv1d/conv1d/kernel:0                [4, 128, 128]    65536
net2/cbhg_mel/conv1d_banks/num_4/normalize/beta:0                      [128]              128
net2/cbhg_mel/conv1d_banks/num_4/normalize/gamma:0                     [128]              128
net2/cbhg_mel/conv1d_banks/num_5/conv1d/conv1d/kernel:0                [5, 128, 128]    81920
net2/cbhg_mel/conv1d_banks/num_5/normalize/beta:0                      [128]              128
net2/cbhg_mel/conv1d_banks/num_5/normalize/gamma:0                     [128]              128
net2/cbhg_mel/conv1d_banks/num_6/conv1d/conv1d/kernel:0                [6, 128, 128]    98304
net2/cbhg_mel/conv1d_banks/num_6/normalize/beta:0                      [128]              128
net2/cbhg_mel/conv1d_banks/num_6/normalize/gamma:0                     [128]              128
net2/cbhg_mel/conv1d_banks/num_7/conv1d/conv1d/kernel:0                [7, 128, 128]   114688
net2/cbhg_mel/conv1d_banks/num_7/normalize/beta:0                      [128]              128
net2/cbhg_mel/conv1d_banks/num_7/normalize/gamma:0                     [128]              128
net2/cbhg_mel/conv1d_banks/num_8/conv1d/conv1d/kernel:0                [8, 128, 128]   131072
net2/cbhg_mel/conv1d_banks/num_8/normalize/beta:0                      [128]              128
net2/cbhg_mel/conv1d_banks/num_8/normalize/gamma:0                     [128]              128
net2/cbhg_mel/conv1d_1/conv1d/kernel:0                                 [3, 1024, 128]  393216
net2/cbhg_mel/normalize/beta:0                                         [128]              128
net2/cbhg_mel/normalize/gamma:0                                        [128]              128
net2/cbhg_mel/conv1d_2/conv1d/kernel:0                                 [3, 128, 128]    49152
net2/cbhg_mel/highwaynet_0/dense1/kernel:0                             [128, 128]       16384
net2/cbhg_mel/highwaynet_0/dense1/bias:0                               [128]              128
net2/cbhg_mel/highwaynet_0/dense2/kernel:0                             [128, 128]       16384
net2/cbhg_mel/highwaynet_0/dense2/bias:0                               [128]              128
net2/cbhg_mel/highwaynet_1/dense1/kernel:0                             [128, 128]       16384
net2/cbhg_mel/highwaynet_1/dense1/bias:0                               [128]              128
net2/cbhg_mel/highwaynet_1/dense2/kernel:0                             [128, 128]       16384
net2/cbhg_mel/highwaynet_1/dense2/bias:0                               [128]              128
net2/cbhg_mel/highwaynet_2/dense1/kernel:0                             [128, 128]       16384
net2/cbhg_mel/highwaynet_2/dense1/bias:0                               [128]              128
net2/cbhg_mel/highwaynet_2/dense2/kernel:0                             [128, 128]       16384
net2/cbhg_mel/highwaynet_2/dense2/bias:0                               [128]              128
net2/cbhg_mel/highwaynet_3/dense1/kernel:0                             [128, 128]       16384
net2/cbhg_mel/highwaynet_3/dense1/bias:0                               [128]              128
net2/cbhg_mel/highwaynet_3/dense2/kernel:0                             [128, 128]       16384
net2/cbhg_mel/highwaynet_3/dense2/bias:0                               [128]              128
net2/cbhg_mel/highwaynet_4/dense1/kernel:0                             [128, 128]       16384
net2/cbhg_mel/highwaynet_4/dense1/bias:0                               [128]              128
net2/cbhg_mel/highwaynet_4/dense2/kernel:0                             [128, 128]       16384
net2/cbhg_mel/highwaynet_4/dense2/bias:0                               [128]              128
net2/cbhg_mel/highwaynet_5/dense1/kernel:0                             [128, 128]       16384
net2/cbhg_mel/highwaynet_5/dense1/bias:0                               [128]              128
net2/cbhg_mel/highwaynet_5/dense2/kernel:0                             [128, 128]       16384
net2/cbhg_mel/highwaynet_5/dense2/bias:0                               [128]              128
net2/cbhg_mel/highwaynet_6/dense1/kernel:0                             [128, 128]       16384
net2/cbhg_mel/highwaynet_6/dense1/bias:0                               [128]              128
net2/cbhg_mel/highwaynet_6/dense2/kernel:0                             [128, 128]       16384
net2/cbhg_mel/highwaynet_6/dense2/bias:0                               [128]              128
net2/cbhg_mel/highwaynet_7/dense1/kernel:0                             [128, 128]       16384
net2/cbhg_mel/highwaynet_7/dense1/bias:0                               [128]              128
net2/cbhg_mel/highwaynet_7/dense2/kernel:0                             [128, 128]       16384
net2/cbhg_mel/highwaynet_7/dense2/bias:0                               [128]              128
net2/cbhg_mel/gru/bidirectional_rnn/fw/gru_cell/gates/kernel:0         [256, 256]       65536
net2/cbhg_mel/gru/bidirectional_rnn/fw/gru_cell/gates/bias:0           [256]              256
net2/cbhg_mel/gru/bidirectional_rnn/fw/gru_cell/candidate/kernel:0     [256, 128]       32768
net2/cbhg_mel/gru/bidirectional_rnn/fw/gru_cell/candidate/bias:0       [128]              128
net2/cbhg_mel/gru/bidirectional_rnn/bw/gru_cell/gates/kernel:0         [256, 256]       65536
net2/cbhg_mel/gru/bidirectional_rnn/bw/gru_cell/gates/bias:0           [256]              256
net2/cbhg_mel/gru/bidirectional_rnn/bw/gru_cell/candidate/kernel:0     [256, 128]       32768
net2/cbhg_mel/gru/bidirectional_rnn/bw/gru_cell/candidate/bias:0       [128]              128
net2/pred_mel/kernel:0                                                 [256, 90]        23040
net2/pred_mel/bias:0                                                   [90]                90
net2/dense/kernel:0                                                    [90, 128]        11520
net2/dense/bias:0                                                      [128]              128
net2/cbhg_linear/conv1d_banks/num_1/conv1d/conv1d/kernel:0             [1, 128, 128]    16384
net2/cbhg_linear/conv1d_banks/num_1/normalize/beta:0                   [128]              128
net2/cbhg_linear/conv1d_banks/num_1/normalize/gamma:0                  [128]              128
net2/cbhg_linear/conv1d_banks/num_2/conv1d/conv1d/kernel:0             [2, 128, 128]    32768
net2/cbhg_linear/conv1d_banks/num_2/normalize/beta:0                   [128]              128
net2/cbhg_linear/conv1d_banks/num_2/normalize/gamma:0                  [128]              128
net2/cbhg_linear/conv1d_banks/num_3/conv1d/conv1d/kernel:0             [3, 128, 128]    49152
net2/cbhg_linear/conv1d_banks/num_3/normalize/beta:0                   [128]              128
net2/cbhg_linear/conv1d_banks/num_3/normalize/gamma:0                  [128]              128
net2/cbhg_linear/conv1d_banks/num_4/conv1d/conv1d/kernel:0             [4, 128, 128]    65536
net2/cbhg_linear/conv1d_banks/num_4/normalize/beta:0                   [128]              128
net2/cbhg_linear/conv1d_banks/num_4/normalize/gamma:0                  [128]              128
net2/cbhg_linear/conv1d_banks/num_5/conv1d/conv1d/kernel:0             [5, 128, 128]    81920
net2/cbhg_linear/conv1d_banks/num_5/normalize/beta:0                   [128]              128
net2/cbhg_linear/conv1d_banks/num_5/normalize/gamma:0                  [128]              128
net2/cbhg_linear/conv1d_banks/num_6/conv1d/conv1d/kernel:0             [6, 128, 128]    98304
net2/cbhg_linear/conv1d_banks/num_6/normalize/beta:0                   [128]              128
net2/cbhg_linear/conv1d_banks/num_6/normalize/gamma:0                  [128]              128
net2/cbhg_linear/conv1d_banks/num_7/conv1d/conv1d/kernel:0             [7, 128, 128]   114688
net2/cbhg_linear/conv1d_banks/num_7/normalize/beta:0                   [128]              128
net2/cbhg_linear/conv1d_banks/num_7/normalize/gamma:0                  [128]              128
net2/cbhg_linear/conv1d_banks/num_8/conv1d/conv1d/kernel:0             [8, 128, 128]   131072
net2/cbhg_linear/conv1d_banks/num_8/normalize/beta:0                   [128]              128
net2/cbhg_linear/conv1d_banks/num_8/normalize/gamma:0                  [128]              128
net2/cbhg_linear/conv1d_1/conv1d/kernel:0                              [3, 1024, 128]  393216
net2/cbhg_linear/normalize/beta:0                                      [128]              128
net2/cbhg_linear/normalize/gamma:0                                     [128]              128
net2/cbhg_linear/conv1d_2/conv1d/kernel:0                              [3, 128, 128]    49152
net2/cbhg_linear/highwaynet_0/dense1/kernel:0                          [128, 128]       16384
net2/cbhg_linear/highwaynet_0/dense1/bias:0                            [128]              128
net2/cbhg_linear/highwaynet_0/dense2/kernel:0                          [128, 128]       16384
net2/cbhg_linear/highwaynet_0/dense2/bias:0                            [128]              128
net2/cbhg_linear/highwaynet_1/dense1/kernel:0                          [128, 128]       16384
net2/cbhg_linear/highwaynet_1/dense1/bias:0                            [128]              128
net2/cbhg_linear/highwaynet_1/dense2/kernel:0                          [128, 128]       16384
net2/cbhg_linear/highwaynet_1/dense2/bias:0                            [128]              128
net2/cbhg_linear/highwaynet_2/dense1/kernel:0                          [128, 128]       16384
net2/cbhg_linear/highwaynet_2/dense1/bias:0                            [128]              128
net2/cbhg_linear/highwaynet_2/dense2/kernel:0                          [128, 128]       16384
net2/cbhg_linear/highwaynet_2/dense2/bias:0                            [128]              128
net2/cbhg_linear/highwaynet_3/dense1/kernel:0                          [128, 128]       16384
net2/cbhg_linear/highwaynet_3/dense1/bias:0                            [128]              128
net2/cbhg_linear/highwaynet_3/dense2/kernel:0                          [128, 128]       16384
net2/cbhg_linear/highwaynet_3/dense2/bias:0                            [128]              128
net2/cbhg_linear/highwaynet_4/dense1/kernel:0                          [128, 128]       16384
net2/cbhg_linear/highwaynet_4/dense1/bias:0                            [128]              128
net2/cbhg_linear/highwaynet_4/dense2/kernel:0                          [128, 128]       16384
net2/cbhg_linear/highwaynet_4/dense2/bias:0                            [128]              128
net2/cbhg_linear/highwaynet_5/dense1/kernel:0                          [128, 128]       16384
net2/cbhg_linear/highwaynet_5/dense1/bias:0                            [128]              128
net2/cbhg_linear/highwaynet_5/dense2/kernel:0                          [128, 128]       16384
net2/cbhg_linear/highwaynet_5/dense2/bias:0                            [128]              128
net2/cbhg_linear/highwaynet_6/dense1/kernel:0                          [128, 128]       16384
net2/cbhg_linear/highwaynet_6/dense1/bias:0                            [128]              128
net2/cbhg_linear/highwaynet_6/dense2/kernel:0                          [128, 128]       16384
net2/cbhg_linear/highwaynet_6/dense2/bias:0                            [128]              128
net2/cbhg_linear/highwaynet_7/dense1/kernel:0                          [128, 128]       16384
net2/cbhg_linear/highwaynet_7/dense1/bias:0                            [128]              128
net2/cbhg_linear/highwaynet_7/dense2/kernel:0                          [128, 128]       16384
net2/cbhg_linear/highwaynet_7/dense2/bias:0                            [128]              128
net2/cbhg_linear/gru/bidirectional_rnn/fw/gru_cell/gates/kernel:0      [256, 256]       65536
net2/cbhg_linear/gru/bidirectional_rnn/fw/gru_cell/gates/bias:0        [256]              256
net2/cbhg_linear/gru/bidirectional_rnn/fw/gru_cell/candidate/kernel:0  [256, 128]       32768
net2/cbhg_linear/gru/bidirectional_rnn/fw/gru_cell/candidate/bias:0    [128]              128
net2/cbhg_linear/gru/bidirectional_rnn/bw/gru_cell/gates/kernel:0      [256, 256]       65536
net2/cbhg_linear/gru/bidirectional_rnn/bw/gru_cell/gates/bias:0        [256]              256
net2/cbhg_linear/gru/bidirectional_rnn/bw/gru_cell/candidate/kernel:0  [256, 128]       32768
net2/cbhg_linear/gru/bidirectional_rnn/bw/gru_cell/candidate/bias:0    [128]              128
net2/pred_spec/kernel:0                                                [256, 569]      145664
net2/pred_spec/bias:0                                                  [569]              569[36m
Total #vars=204, #params=3587856, size=13.69MB[0m
[32m[0130 22:23:11 @base.py:209][0m Setup callbacks graph ...
[32m[0130 22:23:12 @summary.py:38][0m Maintain moving average summary of 0 tensors in collection MOVING_SUMMARY_OPS.
[32m[0130 22:23:12 @summary.py:75][0m Summarizing collection 'summaries' of size 2.
[32m[0130 22:23:19 @common.py:147][0m [4m[5m[31mERR[0m Cannot batch data. Perhaps they are of inconsistent shape?
Traceback (most recent call last):
  File "C:\Users\Yash\anaconda\envs\dlwin36\lib\site-packages\tensorpack\dataflow\common.py", line 145, in _aggregate_batch
    np.asarray([x[k] for x in data_holder], dtype=tp))
  File "C:\Users\Yash\anaconda\envs\dlwin36\lib\site-packages\numpy\core\numeric.py", line 501, in asarray
    return array(a, dtype, copy=False, order=order)
MemoryError
[32m[0130 22:23:19 @common.py:150][0m [4m[5m[31mERR[0m Shape of all arrays to be batched: [(334, 569),
 (334, 569),
 (334, 569),
 (334, 569),
 (334, 569),
 (334, 569),
 (334, 569),
 (334, 569),
 (334, 569),
 (334, 569),
 (334, 569),
 (334, 569),
 (334, 569),
 (334, 569),
 (334, 569),
 (334, 569)]

**Comment by YashBangera7** [comment]
I believe it had something  to do with the set CUDA_VISIBLE_DEVICES=0 keyword .
