### ISSUE TITLE
Error in convert.py . Please can someone help?

### ISSUE THREAD

**Issue by YashBangera7** [andabi/deep-voice-conversion#90]

**Comment by YashBangera7** [comment]
Traceback (most recent call last):
  File "convert.py", line 146, in <module>
    do_convert(args, logdir1=logdir_train1, logdir2=logdir_train2)
  File "convert.py", line 99, in do_convert
    audio, y_audio, ppgs = convert(predictor, df)
  File "convert.py", line 38, in convert
    pred_spec, y_spec, ppgs = predictor(next(df().get_data()))
  File "C:\Users\Yash\anaconda\envs\dlwin36\lib\site-packages\tensorpack\predict\base.py", line 39, in __call__
    output = self._do_call(dp)
  File "C:\Users\Yash\anaconda\envs\dlwin36\lib\site-packages\tensorpack\predict\base.py", line 119, in _do_call
    "{} != {}".format(len(dp), len(self.input_tensors))
AssertionError: 1 != 3

**Comment by MorganCZY** [comment]
I have the same issue. Have u had solved it?

**Comment by YashBangera7** [comment]
> I have the same issue. Have u had solved it?

Yes . #[https://github.com/andabi/deep-voice-conversion/issues/59#issuecomment-420039944](url)
This might help . Just paste the given three lines of code in the do_convert function b efore the aujdio line. This might help . It worked for me ! :)
 By the way , can anyone provide me with the TIMIT dataset that is seperated as test and train ? :)  
You can view the result of conversion in the tensorboard 💯

**Comment by MorganCZY** [comment]
thx, I made it. The loss of Net2 is currently around 0.0055, but the converted voice sounds not well natural, a little bit like artifact. High frequency information is not abundant. 
Ps: I have TIMIT dataset with seperated train and test subfolders.

**Comment by pravn** [comment]
> Yes . #[https://github.com/andabi/deep-voice-conversion/issues/59#issuecomment-420039944](url)

I am having the same problem. The link above does not seem to contain anything.
