### ISSUE TITLE
stuck in train1

### ISSUE THREAD

**Issue by iamxiaoyubei** [andabi/deep-voice-conversion#93]
I have put the TIMIT dataset in the specified location and changed the parameters”wav->WAV“.
![image](https://user-images.githubusercontent.com/21981293/52934460-7653f900-3391-11e9-880b-11de9c87ed4d.png)

![image](https://user-images.githubusercontent.com/21981293/52934263-d7c79800-3390-11e9-989a-4d64747417d6.png)

And I run with "train1_start.sh"scripts like this sh scipts/train1_start.sh case_name gpu_id.
However, I always stuck in train1 like this:

![2019-02-18_153420](https://user-images.githubusercontent.com/21981293/52935011-2413d780-3393-11e9-8b97-cb612102319e.png)

I have tried many methods in the issues similar to my problem, but none of them work for me. I am a newbie, and it is not so easy for me to understand what is wrong with the code. Could someone please help me? Thank you very much!

**Comment by YashBangera7** [comment]
Instead of changing the parameters , try to keep the file format the same and change the code . 
THere must be a .wav and .phn line in the data_load.py code . refer to carlfm01 code. Just change the code and not the file format. Try :/

**Comment by YashBangera7** [comment]
U need .wav not .WAV . I guess.

**Comment by iamxiaoyubei** [comment]
@YashBangera7  Thank you so much!!!

I keep the file format the same("WAV") , change the parameters in default.yaml ("wav"->"WAV") and change a line in the data_load.py code(following line).
![2019-02-18_230321](https://user-images.githubusercontent.com/21981293/52959560-6d831780-33d1-11e9-8a51-deea65785fae.png)

It works! Not stuck in epoch1 now!
![_20190218230019](https://user-images.githubusercontent.com/21981293/52959659-b33fe000-33d1-11e9-98eb-13fbd16b8fab.png)

Thank you again!

**Comment by lee9871** [comment]
i have same problem

**Comment by lee9871** [comment]
@iamxiaoyubei  can you tell me how can i do

**Comment by lee9871** [comment]
![image](https://user-images.githubusercontent.com/56629748/127320091-92ebbe53-0773-4609-93b1-3456391e5b43.png)
![image](https://user-images.githubusercontent.com/56629748/127320136-a1f774b7-77d8-47ab-9f18-d647f6b8c87c.png)
